// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlossomServer.Entities;

public partial class Contact
{
    public int ContactID { get; set; }

    public string Fullname { get; set; }

    public int Phone { get; set; }

    public string Email { get; set; }

    public string Notes { get; set; }

    public string Status { get; set; }

    public DateTime CreatedAt { get; set; }
}