// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlossomServer.Entities;

public partial class MessageChat
{
    public int MessageID { get; set; }

    public int? RoomID { get; set; }

    public Guid? UserID { get; set; }

    public string Message { get; set; }

    public string Status { get; set; }

    public DateTime DateSent { get; set; }
}