// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlossomServer.Entities;

public partial class ResetPassword
{
    public int ResetPasswordID { get; set; }

    public string Username { get; set; }

    public string Code { get; set; }

    public DateTime ExpMinutes { get; set; }

    public bool IsActive { get; set; }
}