// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlossomServer.Entities;

public partial class Room
{
    public Guid RoomID { get; set; }

    public Guid? UserID { get; set; }

    public Guid? ConsultantID { get; set; }
}