// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlossomServer.Entities;

public partial class ServiceImage
{
    public int ImageID { get; set; }

    public string ImageName { get; set; }

    public string ImageURL { get; set; }

    public int? ServiceID { get; set; }

    public string Description { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual Service Service { get; set; }
}