// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlossomServer.Entities;

public partial class ServiceBooking
{
    public int ServiceBookingID { get; set; }

    public int BookingID { get; set; }

    public int ServiceID { get; set; }

    public decimal ServiceCost { get; set; }

    public virtual Booking Booking { get; set; }

    public virtual Service Service { get; set; }
}